---
controller_hosts:
  - name: localhost
    inventory: customer-x-web
    variables:
      some_var: some_val
      ansible_connection: local
  - name: rhel8c.sudo.net
    inventory: customer-x-awx
    variables:
      some_var: some_val
...
